// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PLUGIN_NAME = 'prelura_app';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String OFFER = 'assets/icons/offer.svg';
  static const String TRUSTED = 'assets/icons/trusted.svg';
  static const String LOGO = 'assets/images/logo.png';
  static const String SPLASH = 'assets/images/splash.png';
  static const String TRUSTED = 'assets/svgs/Trusted.svg';
  static const String EMPTY_BOX_ICON = 'assets/svgs/empty-box-icon.svg';
  static const String PIN = 'assets/svgs/pin.svg';
}
