// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String PLUGIN_NAME = 'prelura_app';
  static const String PLUGIN_VERSION = '1.0.0+1';
  static const String COURIERPRIME_REGULAR = 'CourierPrime-Regular';
  static const String INTER_18PT_BLACK = 'Inter_18pt-Black';
  static const String INTER_18PT_BOLD = 'Inter_18pt-Bold';
  static const String INTER_18PT_EXTRABOLD = 'Inter_18pt-ExtraBold';
  static const String INTER_18PT_LIGHT = 'Inter_18pt-Light';
  static const String INTER_18PT_MEDIUM = 'Inter_18pt-Medium';
  static const String INTER_18PT_REGULAR = 'Inter_18pt-Regular';
  static const String INTER_18PT_SEMIBOLD = 'Inter_18pt-SemiBold';
}
